<ul>
    <h4>Additional Links</h4>
    <li><a href="/Users/CPA/cpaDashboard">Open Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaPending">Pending Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaHistory">Closed Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaAccount">Account</a>
    </li>
    <li><a href="/Users/CPA/cpaProfile">Profile</a>
    </li>
    <li><a href="/Users/CPA/cpaDashData">CPA Data Page</a>
    </li>
    <li><a href="/LogOutProcess.aspx">Log Out</a>
    </li>
    <li><a href="/contact-us">Contact Support</a>
    </li>
</ul>