<ul>
    <h4>Additional Links</h4>
    <li><a href="/Users/CPA/cpaDashboard">Open Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaPending">Pending Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaHistory">Closed Tickets</a>
    </li>
    <li><a href="/Users/CPA/cpaAccount">Account</a>
    </li>
    <li><a href="/Users/CPA/cpaProfile">Profile</a>
    </li>
    <li><a href="/contact-us" target="_blank">Contact Support</a>
    </li>
</ul>