<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3"> <img alt="Image" src="/_assets/img/cpalogo1.png" class="mb-4"> </div>
            <div style="opacity:0;" class="col-12 col-md-3">
                <a href="/Users/CPA/cpaDashboard">
                    <div>CPA</div>
                </a>
            </div>
            <div style="opacity:0;" class="col-12 col-md-3">
                <a href="/Users/regionalAdmin/regionalAdmin-dashboard">
                    <div>Regional</div>
                </a>
            </div>
            <div class="col-12 col-md-9 text-right">
                <ul class="socialm">
                    <li>
                        <a href="#" class="nav-link"> <i class="fab fa-facebook-square"></i> </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link"> <i class="fab fa-instagram"></i> </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link"> <i class="fab fa-twitter"></i> </a>
                    </li>
                    <li>
                        <a href="#" class="nav-link"> <i class="fab fa-youtube-square"></i> </a>
                    </li>
                </ul>
            </div>
        </div>
          </div>
        <div class="row btmterm">
            <div class="col-12 col-md-6 left">
                <p>© 2018. All rights reserved. CPA2GO</p>
            </div>    
               <div class="col-12 col-md-6 right"> 
                <ul class="termsnav">
                    <li>
                        <a href="/privacy-policy" class="nav-link">Privacy Policy</a>
                    </li>
                    <li>
                        <a href="/terms-of-service" class="nav-link">Terms of Service</a>
                    </li>
                </ul>
            </div>
            
            
      
    </div>
</footer>