<ul>
    <h4>Account Information</h4>
    <li style="font-weight: bold;"><a href="/Users/customer/ask_a_question">Ask a Question!</a>
    </li>
    <li><a href="/Users/customer/account-dashboard">My Account</a>
    </li>
    <li><a href="/Users/customer/account-history">Account History</a>
    </li>
    <li><a href="/Users/customer/account-settings">Account Settings</a>
    </li>
    <li><a href="/contact-us" target="_blank">Contact Support</a>
    </li>
</ul>